Added individual READMEs for each package
perses/common pull request #20
Opened 2021-07-30 13:42 UTC by AntoineThebaud

2021-07-30 13:56 UTC, Nexucis requested changes
I would prefer that the package description is actually a comments for the corresponding package.

Like that we can also have the golang documention updated in pkg.go.dev

2021-08-06 16:46 UTC, AntoineThebaud commented
Changed README files by additional go doc where relevant

2021-08-06 19:51 UTC, Nexucis requested changes
Excepting two tiny comments, it's really cool !!
Thanks for doing it :)

2021-08-06 19:51 UTC, Nexucis commented on etcd/client.go
> +// This package provides a simple DAO to ease the interaction with ETCD. It also provides a lock system.
In the go doc, you should start by `Package etcd ....`.

2021-08-06 19:51 UTC, Nexucis commented on etcd/client.go
> +// This package provides a simple DAO to ease the interaction with ETCD. It also provides a lock system.
And I think you can remove the extra line between the comment and the name of the package :)

2021-08-06 19:51 UTC, Nexucis commented on slices/contains.go
> +// This package provides utility methods to manipulate slices (mostly slices of string).
In the go doc, you should start by `Package slices.....`

2021-08-06 23:17 UTC, Nexucis commented
nice ! thanks @AntoineThebaud :)

2021-08-06 23:17 UTC, merged